### ISSUE TITLE
关于Meteor中文社区的定名

### ISSUE THREAD

**Issue by laosb** [MeteorChina/workgroup#1]
| 英文名 | 英文缩写 | 中文名 | 票数 |
| --- | --- | --- | --- |
| Meteor China Community | MCC | Meteor中国社区 | 1 |
| Meteor China Community | MCC | Meteor中文社区 | 3 |
| Meteor China Community | MCC | 中国Meteor社区 | 1 |
| Meteor.js.Garden.Community.Cn | MGCC | 流星花园 | 1 |
| vow4meteor | V4M | 流星之盟 | 1 |

**Comment by booxood** [comment]
Meteor中文社区

 +1

**Comment by laosb** [comment]
@booxood 所以英文名？

我把建议都整合一下。

**Comment by yz89** [comment]
Meteor中文社区吧，范围广一些

**Comment by 285858315** [comment]
网站现在有么？

**Comment by yz89** [comment]
https://github.com/meteor-vegas/website 这个模板不错，专门为Meteor Meetup Group设计的

**Comment by fengchenxiujisd** [comment]
流星花园

**Comment by laosb** [comment]
@fengchenxiujisd 请同时给出英文名，因为需要和MDG及全球社区打交道

**Comment by laosb** [comment]
@yz89 好东西，适合线下使用

**Comment by fengchenxiujisd** [comment]
Meteor.js.Garden.Community.Cn

**Comment by carrot93** [comment]
也许可以试试：流星之盟，英文名：vow4Meteor

**Comment by dyh** [comment]
先确定域名，我查了一下，和meteor贴边的好域名不太多啊，MeteorChina基本都没了，只剩下meteorchina.net。
大家多写代码啊～～～
 Linus 大神曾教导过广大程序员“Talk is cheap, show me the code”。

**Comment by booxood** [comment]
我可以贡献 cmeteor.org :laughing:

**Comment by laosb** [comment]
#5

**Comment by laosb** [comment]
关于域名：#5

**Comment by laosb** [comment]
个人意见：支持Meteor China Community, MCC, Meteor中文社区，反对流星花园、流星之盟（江湖气太重）。

**Comment by fengchenxiujisd** [comment]
说的是 不在标题在内容 低调的迎头赶上才是真

**Comment by laosb** [comment]
所以要尽快组织起来，一起开始一些工作。

**Comment by laosb** [comment]
名字可以确定了吗 @fengchenxiujisd @booxood @dyh @yz89 @285858315 @carrot93

**Comment by dyh** [comment]
名字随意定一个。我不是处女座也不是天秤和金牛，没有选择障碍，哈哈哈哈～～～

**Comment by laosb** [comment]
这样的话也就是确定采用Meteor中文社区这个方案了。等待下一个人同意就可以Close了。

**Comment by yz89** [comment]
+1

**Comment by fengchenxiujisd** [comment]
同意 
风风火火的搞起吧

**Comment by carrot93** [comment]
+1 速度

**Comment by laosb** [comment]
好的。定名Meteor中文社区，Meteor China Community, MCC。

**Comment by ilanni2460** [comment]
个人支持 Meteor中文社区
